spring:
  config:
    import: "configserver:"
  application:
    name: transaction-service
  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
