server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/enesincekaraa/bank-config-repo.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          default-label: main
          clone-on-start: true




management:
  endpoints:
    web:
      exposure:
        include: "*"
